### ISSUE TITLE
SEAL break: reissue_set_cookie references crate::web unconditionally, absent in a server-without-web program (E0433)

### ISSUE THREAD

**Issue by arthurmaciel** [arthurmaciel/ipe-lang#1302]
Found by the CLI/FFI-batch guardian's broad run (`golden_authed_store_query_seal` fails). Pre-existing on main; introduced by #1269 P2 (`2c03489d3`).

## Problem
`src/runtime/rust/src/server.rs::reissue_set_cookie` (lines 371, 376) calls `crate::web::csrf::cookies_secure()` and `crate::web::csrf::frame_ancestors()` **unconditionally**, but `pub mod web` (`src/runtime/rust/src/mod.rs:490`) is `#[cfg(feature = "web")]`. An authenticated-route program that uses `Ipe.Http.Server` (+ Db/jwt) but NOT the web/UI shape emits a crate with features `server`+`jwt` and **no `web`** → `crate::web` is absent → `error[E0433]: cannot find 'web' in 'crate'` ×2. `ipe` exits 0, the emitted crate fails `cargo build` — a SEAL breach. Confirmed reproducible in isolation on base main.

## Class
This is the SAME feature-axis SEAL-hole class as:
- #1300 (vendored authed_route: `jwt` feature not added to the emitted defaults → AuthConfig compiled out).
- #1293 (now fixed): web-only program missing `pub mod server` for csrf's `crate::server` re-exports.
All three: an unconditional `crate::X::` reference in the vendored/emitted runtime where module `X` is gated on a feature/`uses_*` that isn't guaranteed present. The now-strengthened modset scanner (#1293) catches this class for the vendored template; the dep model hides it because the runtime crate's own `mod.rs` couples `pub mod X` to `#[cfg(feature="X")]`.

## Fix
The cookie-security helpers `cookies_secure()` / `frame_ancestors()` are needed by the SERVER auth path (`reissue_set_cookie`) but live in `web::csrf`. Either:
1. Relocate `cookies_secure`/`frame_ancestors` to a base/cookie module both `server` and `web` can reach without a `web` dependency (preferred — they read env/config, not web-specific state); or
2. cfg-gate the two `reissue_set_cookie` call sites behind `feature="web"` with a fail-closed non-web fallback (Secure defaults to the production/frame-ancestors signal).

NOTE: `reissue_set_cookie` is also being edited for #1294 (reissue Secure parity) — fix this in the same function to avoid churn.

## Root fix for the whole class (do once all three are closed)
Add a CI lane that runs the SEAL/modset E2E under `IPE_RUNTIME_VENDORED=1 IPE_E2E=1` (`seal_modset`), so the vendored model — currently never exercised in CI — gates this class going forward.

**Comment by arthurmaciel** [comment]
Fixed in e955c5d85. reissue_set_cookie gated its crate::web::csrf::cookies_secure()/frame_ancestors() references behind #[cfg(feature="web")] (the exact condition under which crate::web exists) with a fail-closed production_from_env() fallback for server-only programs. The previously-red golden_authed_store_query_seal::authed_store_query_seal_builds now passes (55s real build); modset 13/13. This closes the server→web instance of the vendored-feature-axis SEAL class.
